apiVersion : apps/v1
kind: Deployment
metadata:
  name: #tenant# 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: #tenant#
  template:
    metadata:
      labels:
        app: #tenant# 
    spec:
      containers:
        - name: #tenant#
          image: sintrasohregistry.azurecr.io/soh-pimcore:latest
          ports:
          - containerPort: 80
          env:
          - name: PIMCORE_DB_HOST
            value: #host#            
          - name: PIMCORE_DB_USER
            value: #user#
          - name: PIMCORE_DB_PSW
            value: #password#
          - name: PIMCORE_DB_NAME
            value: #tenant#
          - name: PIMCORE_DB_PORT
            value: '3306'
