apiVersion : apps/v1
kind: Deployment
metadata:
  name: provacinque 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: provacinque
  template:
    metadata:
      labels:
        app: provacinque 
    spec:
      containers:
        - name: provacinque
          image: sintrasohregistry.azurecr.io/soh-pimcore:latest
          ports:
          - containerPort: 80
          env:
          - name: PIMCORE_DB_HOST
            value: analyticserver01.mysql.database.azure.com            
          - name: PIMCORE_DB_USER
            value: admin01@analyticserver01
          - name: PIMCORE_DB_PSW
            value: Analisidati01
          - name: PIMCORE_DB_NAME
            value: giannan49
