apiVersion : apps/v1
kind: Deployment
metadata:
  name: provatre 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: provatre
  template:
    metadata:
      labels:
        app: provatre 
    spec:
      containers:
        - name: provatre
          image: deploypocmycontainerregistry.azurecr.io/sampleapp
          ports:
          - containerPort: 8080
          env:
          - name: RESPONSE
            value: #customResponse#
