apiVersion : apps/v1
kind: Deployment
metadata:
  name: provaquattro 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: provaquattro
  template:
    metadata:
      labels:
        app: provaquattro 
    spec:
      containers:
        - name: provaquattro
          image: deploypocmycontainerregistry.azurecr.io/sampleapp
          ports:
          - containerPort: 8080
          env:
          - name: RESPONSE
            value: #customResponse#
