apiVersion : apps/v1
kind: Deployment
metadata:
  name: sampleappprova 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sampleappprova
  template:
    metadata:
      labels:
        app: sampleappprova 
    spec:
      containers:
        - name: sampleappprova
          image: deploypocmycontainerregistry.azurecr.io/sampleapp
          ports:
          - containerPort: 8080
          env:
          - name: RESPONSE
            value: #customResponse#
