apiVersion: v1
kind: Service
metadata:
    name: sampleapp
    annotations:
        service.beta.kubernetes.io/azure-dns-label-name: sintralabpimcoredeploy
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 8080
    selector:
        app: sampleapp
