apiVersion: v1
kind: Service
metadata:
    annotations:
        service.beta.kubernetes.io/azure-dns-label-name: sintraprovatre
    name: provatre
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 8080
    selector:
        app: provatre
